name: Run Selenium tests and publish web-app

env:
  AZURE_WEBAPP_NAME: CarefulBitesAPI20221128134821    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.100'                           # set this to the .NET Core version to use

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'Testing'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Send request to API to ensure DB is awake
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://carefulbitesapi20221128134821.azurewebsites.net/CarefulBites/foodItems'
        method: 'GET'
        customHeaders: '{"Content-Type": "application/json"}'
        retry_on: error
    
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
          
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.1.0
        
    - name:  Install Google Chrome 
      run: |
        chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Test
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1920x1080x24 > /dev/null 2>&1 & # optional
        python -m http.server --directory /home/runner/work/CarefulBitesFrontendAndSelenium/CarefulBitesFrontendAndSelenium/CarefulBites_Front-end --bind 127.0.0.1 9000 &
        dotnet test './CarefulBitesSelenium/' --configuration Release
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: web-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: web-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
